name: Git Hosted test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: List the files
        run: |
          ls -a

      - name: Read files
        run: |
          cat .github/workflows/example.txt
